### ISSUE TITLE
Auto-generate docs for using the CLI tools

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#128]
Bartek can you elaborate more on this?

- [ ] When I run `ibc-relayer start --help` for example, it doesn't show the default values. It would be good to output that somehow. (This requires changing how we integrate with commander, or swapping out commander)

**Comment by bartmacbartek** [comment]
The "architecture" looks like this:
```
INPUT --> [commander] --> [options-resolver] --> [run] --> OUTPUT
```

- commander
  - contains command & its options definition
  - parses cli flags
  - generates command help


- options-resolver
  - resolves options based on importance (flag > app file > env etc.)
  - forwards them to `run`

`commander` step is responsible for generating the help message. It's unaware of `options-resolver` step and thus it's omitting some information such as default option value.

We cannot merge `options-resolver` step into `commander` because it contains inter references and async operations.

Moving the default option definition from `options-resolver` to `commander` resolves the problem with the help message, however, it creates another one. If a user doesn't provide a flag then a default value is used and it's going to be picked up in the `options-resolver` step:
```ts
  const poll = resolveOption('poll', { required: true, integer: true })(
    flags.poll, // <-- resolved as first while it should be the last choice
    process.env.RELAYER_POLL,
  );
```

I have a solution to this but IMO it gives too much room for an error:
```ts
  const poll = resolveOption('poll', { required: true, integer: true })(
    notDefault(flags.poll), // <-- wrapping with notDefault returns a value only if provided by an user
    process.env.RELAYER_POLL,
    flags.poll, // <-- default value
  );

  function notDefault(...) {
    // checks if option is in process.argv (it means it was provided by an user)
  }
```

The `commander.js` or `yargs` don't provide any metadata with parsed option (e.g. if default is used).

---

The other problem is that currently we define `Flags` type by hand. It must be maintained and can lead to errors:
```ts
const startCommand = program
  .addOption(homeOption)
  .addOption(srcOption)
  .addOption(destOption)
  ...

type Flags = {
  home?: string
  src?: string
  dest?: string
}

/*
change in startCommand has to be applied to Flags type too. they're not
in sync and we don't test the whole options-resolvers. this is not reliable
*/
```

Ideally, I would like to get the type from where the options are defined. I found it's possible with `yargs`: https://github.com/yargs/yargs/blob/master/docs/typescript.md (first two code blocks). However, I have issues applying this technique with multiple commands in one binary (our case).

---

**Summary**
I'm still looking for the best solution and I put a lot of hope in `yargs`. For now, I'm going to define defaults as a part of the description and will come back to it when I have some more time.

**Comment by ethanfrey** [comment]
> For now, I'm going to define defaults as a part of the description and will come back to it when I have some more time.

Sounds sensible. Let's just do that with docstrings now, and revisit this when the pending higher priority items are resolved

**Comment by willclarktech** [comment]
@bartmacbartek Your nice diagram showing the flow of the application makes it pretty clear there's no easy solution here: if commander isn't responsible for options processing then we don't get any of the benefits of using commander's options processing, eg knowing about default values for help messages. The solution you posted muddies the responsibilities of the different components so (like you) I don't like it. I think manually adding the default values is the best option for the current architecture with the (relatively stable, relatively small number of) options we currently have.

**Comment by ethanfrey** [comment]
We can close this (or drag to bottom of the backlog), right?
