### ISSUE TITLE
Provide way to query all channels for a connection 

### ISSUE THREAD

**Issue by orkunkl** [confio/ts-relayer#140]
Currently there is not way to determine which channel the relayer is processing. Would be great to see it in app.yaml. Also this could may help when migrating relayer process to another machine.

**Comment by ethanfrey** [comment]
A relayer will relay all channels in one connection.

The problem is we have no good way of listing them all. Maybe @bartmacbartek can link some code that helps list?

Also, the log message when creating a channel is not very good and if you miss that, there is no reference of what channel to use to send on. We definitely need a better workflow there.

Can you explain some user workflows you want? I don't agree with the `app.yaml` solution, but I agree with the problem

**Comment by orkunkl** [comment]
If relayer will work in one connection then this gets simpler I think. Writing the available channels to a file does not make sense and not needed. Instead a `ibc-setup channels list <connection-id>` or `ibc-setup connections list-channels <connection-id>` would do the work.

**Comment by ethanfrey** [comment]
Hopefully https://github.com/confio/ts-relayer/issues/54 will produce better output when creating the channel.
I agree with the utility of adding that query command. Maybe @bartmacbartek has some ideas on the exact syntax?

**Comment by bartmacbartek** [comment]
`ibc-setup channels` command already implements filtering on `port` with `--port` cli flag. I would add `--connection` flag (or `--connection-id`) to it to filter by connection.

Does it work for you?

**Comment by ethanfrey** [comment]
Yup, that would be a good solution. Query all and filter in the client. (And one day in the server when it supports it)
