### ISSUE TITLE
Demo relayer lib in webapp

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#142]
The `lib` dir should work in both node and browser (react app).

Make a simple app that maybe replicates some subset of `ibc-relayer start) as a webapp. It can take an ugly form for setup (instead of app.yaml) and maybe has a hardcoded registry file inside you must select from. But it should work between some testnets so we can demo a browser app relaying packets.

Someone else can take this and make something useful with it.

**Comment by ethanfrey** [comment]
@clockworkgr 
I know you were working on a web app that importing `ts-relayer` lib. Could you link something here? It would be better than any dummy example we could make

**Comment by clockworkgr** [comment]
@ethanfrey We have the implementation in Starport interface (https://github.com/tendermint/vue) but it's quite complicated

I've ported the relevant parts over to a very simple Vue app and will be posting a link here when completed in the next day or so

**Comment by ethanfrey** [comment]
Thank you very much Alex

**Comment by clockworkgr** [comment]
https://github.com/clockworkgr/ts-relayer-example there you go

**Comment by clockworkgr** [comment]
and this what it looks like (tested with 2 starport launched chains...)
![image](https://user-images.githubusercontent.com/6826762/116312118-b3f40e00-a7b4-11eb-879b-ce3135764460.png)

**Comment by ethanfrey** [comment]
Very cool!

I also noticed we should make our imports easier to use: `import { IbcClient, Link } from "@confio/relayer/build";`
Maybe we can avoid the `build` part with better configs.

But awesome to see this working in a browser. Thank you! :pray:

**Comment by clockworkgr** [comment]
> Very cool!
> 
> I also noticed we should make our imports easier to use: `import { IbcClient, Link } from "@confio/relayer/build";`
> Maybe we can avoid the `build` part with better configs.
> 
> But awesome to see this working in a browser. Thank you!

needs a "main" entry in package.json pointing to a file that exports what needs to be exportable

"main": "./build/index.ts" should do it.

**Comment by clockworkgr** [comment]
Also...something I couldn't be bothered to debug:

Using a string for timeoutTimestamp doesn't work as it dies within your IBC transfer codec because of an isZero() check (which obviously strings don't have, hence I passed a Long instance directly.

Our codec (auto-generated by starport using protoc) looks like this: https://github.com/tendermint/vue/blob/develop/packages/template/src/store/generated/cosmos/cosmos-sdk/ibc.applications.transfer.v1/module/types/ibc/applications/transfer/v1/tx.js

And I'm wondering what (and more importantly why) is different in the process to generate these codecs between starport and cosmsjs

**Comment by clockworkgr** [comment]
@ethanfrey if you want me to change/polish anything for this let me know

**Comment by ethanfrey** [comment]
Hi @clockworkgr thanks for bumping this. I was on vacation last week. Happy to add these links to the README in the next day or two. Nothing missing on your end.
