### ISSUE TITLE
Tx was submitted but was not yet found on the chain

### ISSUE THREAD

**Issue by mark-microtick** [confio/ts-relayer#180]
Using both the latest release and the latest commti on main (650bccd) cannot setup a channel.

$ ibc-setup ics20
Used existing connections [gaiad-microtick-testnet, connection-1, 07-tendermint-1] <=> [microtick-testnet-rc6, connection-0, 07-tendermint-0]
info: Create channel with sender gaiad-microtick-testnet: transfer => transfer
(node:451751) UnhandledPromiseRejectionWarning: Error: Transaction with ID B92AE5B89D5BF39C63D59A5E22D7272201113FCB991AA155477D2B145FEF0628 was submitted but was not yet found on the chain. You might want to check later.

Correction: The transaction eventually does appear, but not before it times out apparently

**Comment by mark-microtick** [comment]
gaiad version v4.2.1
microtick is built with SDK 0.42.4

**Comment by ethanfrey** [comment]
@webmaster128 this is likely due to the new timeout in cosmjs. 

Mark, there is an issue to make this configurable for shorter and longer block times.

What are your typical block times? Are you using low gas, such that it wait several blocks before anyone broadcasts it? If you blocktime is less than 10s, i would increase gas price and see if that works

**Comment by mark-microtick** [comment]
So I tried again just increasing gas and it doesn't seem to have an effect.  Only increasing the timeout seems to work here.

**Comment by mark-microtick** [comment]
I don't know what I did before to get it to work.  After restarting the testnet, I can't get the 
```
$ ibc-setup ics
```
step to work now, even changing the gas and the timeouts.

**Comment by webmaster128** [comment]
This is probably fixed when upgrading CosmJS to 0.25.3.
